<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\Unit;
use App\Models\Position;
use App\Models\Rank;
use App\Models\Religion;

class EmployeesSeeder extends Seeder
{
    public function run()
    {
        $religion = Religion::firstOrCreate(['name' => 'Islam']);

        $employees = [
            [
                'nip' => '12130569001',
                'first_name' => 'Saifulloh',
                'last_name' => 'Rifai',
                'birth_place' => 'Banjarnegara',
                'birth_date' => '1968-03-15',
                'address' => 'Jl. Melon No.16 Dian Asri',
                'gender' => 'L',
                'rank_code' => 'IV/e',
                'position_name' => 'Kepala Sekretariat Utama',
                'unit_name' => 'Jakarta',
            ],
            [
                'nip' => '12130569002',
                'first_name' => 'Ahmad',
                'last_name' => 'Fauzi',
                'birth_place' => 'Jakarta',
                'birth_date' => '1968-08-27',
                'address' => 'Jl. Golf Komp Bakosurtanal No.39',
                'gender' => 'L',
                'rank_code' => 'IV/a',
                'position_name' => 'Penyusun Laporan Keuangan',
                'unit_name' => 'Keuangan',
            ],
            [
                'nip' => '12130569003',
                'first_name' => 'Ridwan',
                'last_name' => 'Siregar',
                'birth_place' => 'Bekasi',
                'birth_date' => '1987-07-10',
                'address' => 'Jl.Mendut III, Puri Nirwana I RT.03/16',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Pertama',
                'unit_name' => 'Pemetaan',
            ],
            [
                'nip' => '12130569004',
                'first_name' => 'Hendra',
                'last_name' => 'Wijaya',
                'birth_place' => 'Yogyakarta',
                'birth_date' => '1987-05-03',
                'address' => 'Perum Jombor Baru',
                'gender' => 'L',
                'rank_code' => 'III/b',
                'position_name' => 'Analis Data Survei dan Pemetaan',
                'unit_name' => 'Data & Analitik',
            ],
            [
                'nip' => '12130569005',
                'first_name' => 'Tri',
                'last_name' => 'Santoso',
                'birth_place' => 'Trenggalek',
                'birth_date' => '1992-07-07',
                'address' => 'Trengalek',
                'gender' => 'L',
                'rank_code' => 'III/a',
                'position_name' => 'Perancang Peraturan Perundangan',
                'unit_name' => 'Hukum',
            ],
            [
                'nip' => '12130569006',
                'first_name' => 'Slamet',
                'last_name' => 'Hidayat',
                'birth_place' => 'Jakarta',
                'birth_date' => '1963-06-05',
                'address' => 'Bella Casa Residence Blok E.1 No.9',
                'gender' => 'L',
                'rank_code' => 'IV/c',
                'position_name' => 'Kepala Biro Perencanaan & Kepegawaian',
                'unit_name' => 'Perencanaan',
            ],
            [
                'nip' => '12130569007',
                'first_name' => 'Sutrisno',
                'last_name' => 'Adinata',
                'birth_place' => 'Bogor',
                'birth_date' => '1952-11-07',
                'address' => 'Jl Pelita I/18 Kedung Halang Talang',
                'gender' => 'L',
                'rank_code' => 'IV/e',
                'position_name' => 'Widyaiswara Utama',
                'unit_name' => 'Pelatihan',
            ],
            [
                'nip' => '12130569008',
                'first_name' => 'Mulyadi',
                'last_name' => 'Rahman',
                'birth_place' => 'Cikaret',
                'birth_date' => '1954-09-12',
                'address' => 'Komp. BAKOSURTANAL CIKARET',
                'gender' => 'L',
                'rank_code' => 'IV/e',
                'position_name' => 'Ahli Pemetaan Senior',
                'unit_name' => 'Bakosurtanal',
            ],
            [
                'nip' => '12130569009',
                'first_name' => 'Agus',
                'last_name' => 'Suharto',
                'birth_place' => 'Bandung',
                'birth_date' => '1966-11-30',
                'address' => 'Cigadung Selatan II/135',
                'gender' => 'L',
                'rank_code' => 'IV/d',
                'position_name' => 'Kepala Bidang Operasional',
                'unit_name' => 'Operasional',
            ],
            [
                'nip' => '12130569010',
                'first_name' => 'Eko',
                'last_name' => 'Nugroho',
                'birth_place' => 'Bogor',
                'birth_date' => '1962-12-04',
                'address' => 'Jl Raya Tegar Beriman Gg H Jairan No 116',
                'gender' => 'L',
                'rank_code' => 'IV/c',
                'position_name' => 'Analis Kepegawaian Madya',
                'unit_name' => 'Kepegawaian',
            ],
            // 11–25: lebih ringkas tapi tetap natural dan konsisten
            [
                'first_name' => 'Budi',
                'last_name' => 'Hartono',
                'birth_place' => 'Jakarta',
                'birth_date' => '1963-07-03',
                'address' => 'Jl. Merpati No.21',
                'gender' => 'L',
                'rank_code' => 'IV/b',
                'position_name' => 'Analis Kebijakan',
                'unit_name' => 'Administrasi',
            ],
            [
                'first_name' => 'Rizal',
                'last_name' => 'Akbar',
                'birth_place' => 'Depok',
                'birth_date' => '1970-08-22',
                'address' => 'Jl.Kupu-kupu Blok NJ 16 RT.03/09',
                'gender' => 'L',
                'rank_code' => 'IV/a',
                'position_name' => 'Kepala Sub Bidang Kerjasama',
                'unit_name' => 'DKP',
            ],
            [
                'first_name' => 'Imam',
                'last_name' => 'Sulaiman',
                'birth_place' => 'Bogor',
                'birth_date' => '1958-10-11',
                'address' => 'Kp. Sawah RT.01/11 No.27',
                'gender' => 'L',
                'rank_code' => 'III/d',
                'position_name' => 'Analis Hukum',
                'unit_name' => 'Hukum',
            ],
            [
                'first_name' => 'Rahmat',
                'last_name' => 'Wicaksono',
                'birth_place' => 'Sukabumi',
                'birth_date' => '1967-12-14',
                'address' => 'Jl. Kebon Pedes Gang Pacilong No. 4',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Peneliti Pertama',
                'unit_name' => 'Riset',
            ],
            [
                'first_name' => 'Dwi',
                'last_name' => 'Santosa',
                'birth_place' => 'Bogor',
                'birth_date' => '1983-04-09',
                'address' => 'Jl Setasiun No 294 RT 06 RW 01',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Bayu',
                'last_name' => 'Pratama',
                'birth_place' => 'Bekasi',
                'birth_date' => '1983-08-04',
                'address' => 'Perum Delivina Blok A.4/6',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Hafiz',
                'last_name' => 'Nugraha',
                'birth_place' => 'Cimahi',
                'birth_date' => '1962-08-14',
                'address' => 'Jln.Golf Ling. 2 Citatah Dalam No.21',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Dadan',
                'last_name' => 'Firmansyah',
                'birth_place' => 'Bogor',
                'birth_date' => '1973-02-21',
                'address' => 'Jl. Ciliwung BCE RT.07/11',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Irfan',
                'last_name' => 'Saputra',
                'birth_place' => 'Bogor',
                'birth_date' => '1974-04-29',
                'address' => 'Kp. Kandang',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Roni',
                'last_name' => 'Utama',
                'birth_place' => 'Depok',
                'birth_date' => '1975-12-28',
                'address' => 'Jl. Garuda Gg. Mangga RT002',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Analis Jabatan',
                'unit_name' => 'Administrasi',
            ],
            [
                'first_name' => 'Agung',
                'last_name' => 'Herlambang',
                'birth_place' => 'Bogor',
                'birth_date' => '1979-03-26',
                'address' => 'Perum Puri Karadenan Blok C 7',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Taufik',
                'last_name' => 'Ramadhan',
                'birth_place' => 'Bogor',
                'birth_date' => '1979-06-12',
                'address' => 'Jl. Satsiun No.225 RT.02/02',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Edy',
                'last_name' => 'Mahendra',
                'birth_place' => 'Depok',
                'birth_date' => '1980-01-11',
                'address' => 'Jl. Prambanan RT.12/16 Pabuaran',
                'gender' => 'L',
                'rank_code' => 'III/c',
                'position_name' => 'Surveyor Pemetaan Muda',
                'unit_name' => 'Pemetaan',
            ],
            [
                'first_name' => 'Sari',
                'last_name' => 'Anindita',
                'birth_place' => 'Bandung',
                'birth_date' => '1980-03-06',
                'address' => 'Jl. Merpati Indah No.2',
                'gender' => 'P',
                'rank_code' => 'III/c',
                'position_name' => 'Kepala Subbag Kepegawaian',
                'unit_name' => 'Kepegawaian',
            ],
        ];

        foreach ($employees as $row) {
            $unit = Unit::firstOrCreate(['name' => $row['unit_name'] ?? 'Umum']);
            $rank = Rank::firstOrCreate(['code' => $row['rank_code'] ?? 'III/c']);
            $position = Position::firstOrCreate(['name' => $row['position_name'] ?? 'Staf']);

            Employee::create([
                'nip' => $row['nip'] ?? null,
                'first_name' => $row['first_name'],
                'last_name' => $row['last_name'] ?? '',
                'birth_place' => $row['birth_place'] ?? '',
                'birth_date' => $row['birth_date'] ?? null,
                'gender' => $row['gender'] ?? 'L',
                'rank_id' => $rank->id,
                'position_id' => $position->id,
                'unit_id' => $unit->id,
                'religion_id' => $religion->id,
                'address' => $row['address'] ?? '',
            ]);
        }
    }
}
